package vkx.baogia.model;
// Generated Nov 25, 2015 9:29:32 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name = "job")
public class Job implements java.io.Serializable {

	private Integer jobId;
	private String jobName;
	private String jobDesc;

	public Job() {
	}

	public Job(String jobName, String jobDesc) {
		this.jobName = jobName;
		this.jobDesc = jobDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "job_id", unique = true, nullable = false)
	public Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	@Column(name = "job_name", length = 45)
	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	@Column(name = "job_desc", length = 16777215)
	public String getJobDesc() {
		return this.jobDesc;
	}

	public void setJobDesc(String jobDesc) {
		this.jobDesc = jobDesc;
	}

}
